logging:
  level:
    org.springframework.cloud.gateway: TRACE

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://authservice:8080
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
            - id: doctor-service
              uri: http://doctor-service:8086
              predicates:
                - Path=/api/doctors/**
              filters:
                - StripPrefix=1
            - id: patient-service
              uri: http://patient-service:8082
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
            - id: patient-calendar-service
              uri: http://patient-service:8082
              predicates:
                - Path=/api/calendar/**
              filters:
                - StripPrefix=1
            - id: prescription-service
              uri: http://prescription-service:8083
              predicates:
                - Path=/api/prescriptions/**
              filters:
                - StripPrefix=1
            - id: medicine-service
              uri: http://medicine-service:8084
              predicates:
                - Path=/api/medicines/**
              filters:
                - StripPrefix=1
            - id: pdf-service
              uri: http://pdf-service:8085
              predicates:
                - Path=/api/pdf/**
              filters:
                - StripPrefix=1
            - id: receptionist-service
              uri: http://receptionist-service:8087
              predicates:
                - Path=/api/receptionists/**
              filters:
                - StripPrefix=1
