spring.application.name=doctor-service
server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/doctor_db
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.maximumPoolSize=5

# Backblaze B2 S3 Configuration
app.s3.endpoint=${S3_ENDPOINT:https://s3.ca-east-006.backblazeb2.com}
app.s3.bucket-name=${S3_BUCKET_NAME:8d47dcfb84c6a6969fd20310}
app.s3.access-key-id=${S3_ACCESS_KEY_ID}
app.s3.secret-access-key=${S3_SECRET_ACCESS_KEY}
app.s3.region=${S3_REGION:ca-east-006}